services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    image: exampleuser/exampleapp:latest # Usando a imagem do Docker Hub
    container_name: nextjs_container
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      PORT: 4000 # 🔹 Definindo explicitamente a porta
      NEXTAUTH_URL: "http://localhost:4000"
      GOOGLE_CLIENT_ID: "example-google-client-id"
      GOOGLE_CLIENT_SECRET: "example-google-client-secret"
      NEXTAUTH_SECRET: "example-nextauth-secret"
      DATABASE_URL: "postgresql://example_user:example_password@postgres:5432/example_db"
      FORCE_ADMIN: "true" # Forçar criação de usuário como administrador por padrão

volumes:
  postgres_data:
